/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.KhoDoUong_DAO;
import POJO.KhoDoUong;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HELLO TRƯỜNG AN
 */
public class QuanLyNhapKho extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyNhapKho
     */
    KhoDoUong_DAO khoDoUongDAO = new KhoDoUong_DAO();
    public KhoDoUong_DAO kdu_dao;
    DefaultTableModel dtm = new DefaultTableModel();
    List <KhoDoUong> listdu = new ArrayList<>();
    public QuanLyNhapKho() {
        initComponents();
        this.setTitle("Quản Lý Đồ Uống");
        this.setLocationRelativeTo(null);
        String []tieuDe = {"Mã Đồ Uống", "Số lượng"};
        dtm.setColumnIdentifiers(tieuDe);
        tb_danhSachKhoDoUong.setModel(dtm);
        loadDataNhapKho();
    }
    public void loadDataNhapKho(){
        List <KhoDoUong> list = KhoDoUong_DAO.getAllKhoDoUong();
        DefaultTableModel modelDU= (DefaultTableModel) tb_danhSachKhoDoUong.getModel();
        modelDU.setRowCount(0);
        for (KhoDoUong du: list) {
          modelDU.addRow(new Object[] {
           du.getMaDoUong(),du.getSoLuong()
          });
        }
    }   
    public void clearTextField(){
        txt_maDoUong.setText("");
        txt_maDoUong.setEditable(true);
        txt_soLuong.setText("");
        txt_maDoUong.requestFocus();
    }
    public void loadDuLieuTextBox(){
        int row = this.tb_danhSachKhoDoUong.getSelectedRow();
        this.txt_maDoUong.setText((String)(tb_danhSachKhoDoUong.getValueAt(row, 0).toString()));
        this.txt_maDoUong.setEditable(false);
        this.txt_soLuong.setText((String)(tb_danhSachKhoDoUong.getValueAt(row, 1).toString()));
    }
    private void searchKhoDoUong() {
        // Lấy nội dung từ JTextField txt_timKiemTheoTen
        String keyword = txt_timKiemTheoTen.getText().trim();

        // Kiểm tra keyword có chứa khoảng trắng hoặc không
        if (keyword.trim().equals("")) {
            loadDataNhapKho();
            return;
        }
        // Tạo danh sách kết quả tìm kiếm
        List<KhoDoUong> result = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) tb_danhSachKhoDoUong.getModel(); // Lấy data model của JTable
        for (int i = 0; i < model.getRowCount(); i++) {
            KhoDoUong kdu = new KhoDoUong();
            kdu.setMaDoUong((int) model.getValueAt(i, 0));
            kdu.setSoLuong((int) model.getValueAt(i, 1));
            if (String.valueOf(kdu.getMaDoUong()).contains(keyword.toLowerCase())) {
                result.add(kdu);
            }
        }
        model.setRowCount(0); // xoá tất cả các dòng trong JTable
        for (KhoDoUong kdu : result) {
            Object[] row = {kdu.getMaDoUong(), kdu.getSoLuong()};
            model.addRow(row); // thêm dòng mới vào JTable
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_danhSachKhoDoUong = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnTroLai = new javax.swing.JButton();
        txt_timKiemTheoTen = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_maDoUong = new javax.swing.JTextField();
        txt_soLuong = new javax.swing.JTextField();
        btn_xoaKho = new javax.swing.JButton();
        btn_themKho = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_danhSachKhoDoUong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_danhSachKhoDoUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_danhSachKhoDoUongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_danhSachKhoDoUong);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NHẬP KHO");

        btnTroLai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTroLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Go Back_50px.png"))); // NOI18N
        btnTroLai.setText("Trở lại");
        btnTroLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnTroLai)
                .addGap(91, 91, 91)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTroLai, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mã đồ uống:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Số lượng:");

        btn_xoaKho.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_xoaKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        btn_xoaKho.setText("Xóa");
        btn_xoaKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaKhoActionPerformed(evt);
            }
        });

        btn_themKho.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_themKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new product.png"))); // NOI18N
        btn_themKho.setText("Thêm");
        btn_themKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themKhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_themKho)
                        .addGap(67, 67, 67)
                        .addComponent(btn_xoaKho)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_maDoUong)
                            .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_maDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xoaKho, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_themKho, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt_timKiemTheoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_timKiemTheoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiem))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void tb_danhSachKhoDoUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_danhSachKhoDoUongMouseClicked
        loadDuLieuTextBox();
    }//GEN-LAST:event_tb_danhSachKhoDoUongMouseClicked

    private void btnTroLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroLaiActionPerformed
        QuanLyChung qlc = new QuanLyChung();
        qlc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTroLaiActionPerformed

    private void btn_xoaKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaKhoActionPerformed
        // TODO add your handling code here:
        int row = tb_danhSachKhoDoUong.getSelectedRow();
        KhoDoUong_DAO khoDU_DAO = new KhoDoUong_DAO();
        String maDU = (String) tb_danhSachKhoDoUong.getValueAt(row, 0).toString();
        int action =JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa không?","Delete?",JOptionPane.YES_NO_OPTION);
        DefaultTableModel model=(DefaultTableModel) tb_danhSachKhoDoUong.getModel();
        if(action==JOptionPane.YES_OPTION) {
            khoDU_DAO.DeleteKhoDoUong(maDU);
        }
        JOptionPane.showMessageDialog(null, "Ok");
        model.removeRow(row);
        loadDataNhapKho();
    }//GEN-LAST:event_btn_xoaKhoActionPerformed

    private void btn_themKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themKhoActionPerformed
        // TODO add your handling code here:
        KhoDoUong kdu =new KhoDoUong();
        kdu.setMaDoUong(Integer.parseInt(txt_maDoUong.getText()));
        kdu.setSoLuong(Integer.parseInt(txt_soLuong.getText()));
        KhoDoUong_DAO kdu_dao = new KhoDoUong_DAO();
        listdu.add(kdu);
        if(kdu_dao.ThemKhoDoUong(kdu)) {
            JOptionPane.showMessageDialog(null, "Thêm thành công!");
        }else {
            JOptionPane.showMessageDialog(null, "Thêm thất bại!");
        }
        loadDataNhapKho();
    }//GEN-LAST:event_btn_themKhoActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        searchKhoDoUong();
        clearTextField();

    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhapKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTroLai;
    private javax.swing.JButton btn_themKho;
    private javax.swing.JButton btn_xoaKho;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_danhSachKhoDoUong;
    private javax.swing.JTextField txt_maDoUong;
    private javax.swing.JTextField txt_soLuong;
    private javax.swing.JTextField txt_timKiemTheoTen;
    // End of variables declaration//GEN-END:variables
}
