/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class ThongKe_SPBC extends javax.swing.JFrame {

    /**
     * Creates new form ThongKe_SPBC
     */
    private JTable table;
    private DefaultTableModel model;

    public ThongKe_SPBC() {
        super("Top 5 sản phẩm bán chạy nhất");

        // Khởi tạo bảng và mô hình dữ liệu
        table = new JTable();
        model = new DefaultTableModel();
        model.addColumn("Tên sản phẩm");
        model.addColumn("Tổng số lượng bán");
        table.setModel(model);

        // Lấy dữ liệu từ CSDL và thêm vào bảng
        try (Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=QL_CaFe", "sa", "thaint2002")) {
            String sql = "{CALL GetTop5SanPhamBanChay()}";
            CallableStatement stmt = con.prepareCall(sql);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                String tenSP = rs.getString("TenDoUong");
                int soLuongBan = rs.getInt("TongSoLuongBan");
                Vector row = new Vector();
                row.add(tenSP);
                row.add(soLuongBan);
                model.addRow(row);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        // Thêm bảng vào giao diện
        JScrollPane scrollPane = new JScrollPane(table);
        add(scrollPane, BorderLayout.CENTER);

        // Thêm nút Back vào giao diện
        JButton backButton = new JButton("Trở Về");
        add(backButton, BorderLayout.SOUTH);

        // Cấu hình ActionListener cho nút Back
        backButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                QuanLyThongKe qlc = new QuanLyThongKe();
                qlc.setVisible(true);
                dispose();
                // Show the previous JFrame here
            }
        });

        // Cấu hình giao diện
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe_SPBC().setVisible(true);
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
